(when (eq system-type 'darwin)
          (prelude-swap-meta-and-super)
          (exec-path-from-shell-initialize)
      (eq system-type 'windows-nt)
          (setq w32-pass-lwindow-to-system nil)
          (setq w32-pass-rwindow-to-system nil)
          (setq w32-pass-apps-to-system nil)
          (setq w32-lwindow-modifier 'super)
          (setq w32-rwindow-modifier 'super)
          (setq w32-apps-modifier 'hyper))
